keys:
  - &gpg_h7x4 F7D37890228A907440E1FD4846B9228E814A2AAC
  - &host_tsuki age1c92j4w0gqh32hwssl5m2mfrggssxax9pge8qxwytv9lmrnfttcvqdrgsst

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env)$
    key_groups:
      - pgp:
        - *gpg_h7x4
        age:
        - *host_tsuki
