{ pkgs, machineVars, ... }:
{
  home.packages = with pkgs; [
    asciidoctor
    beets
    biber
    python39Packages.bpython
    broot
    castnow
    cheat
    cli-visualizer
    cloc
    czkawka
    delta
    diskonaut
    diskus
    docker
    dogdns
    du-dust
    duf
    duff
    epr
    fd
    ffmpeg
    glances
    googler
    # gpgtui
    gping
    graphviz
    hck
    hexyl
    httpie
    icdiff
    imagemagick
    ipcalc
    jq
    kepubify
    keymapviz
    lastpass-cli
    lazydocker
    lolcat
    manix
    mcfly
    mdcat
    mdp
    mediainfo
    megacmd
    megasync
    micro
    mkvtoolnix
    mmv
    mps-youtube
    mtr
    neofetch
    nix-diff
    nix-index
    nix-output-monitor
    nix-tree
    nix-zsh-completions
    nixops
    nmap
    ouch
    pandoc
    python3
    rclone
    ripgrep
    rsync
    rust-motd
    sc-im
    sd
    slack-term
    taskwarrior
    taskwarrior-tui
    tea
    tealdeer
    terminal-parrot
    termtosvg
    # tv-renamer
    toilet
    tokei
    tsukae
    unpaper
    w3m
    waifu2x-converter-cpp
    watchexec
    wavemon
    wiki-tui
    youtube-dl

    # Needed for VSCode liveshare
    desktop-file-utils
    krb5
    zlib
    icu
    openssl
    xorg.xprop
  ] ++ (
    lib.optionals (!machineVars.headless) [
      ahoviewer
      anki
      audacity
      calibre
      cool-retro-term
      copyq
      darktable
      discord
      fcitx
      geogebra
      gnome.gnome-font-viewer
      google-chrome
      inkscape
      insomnia
      kid3
      koreader
      krita
      ktouch
      libreoffice-fresh
      light
      maim
      mopidy
      mopidy-mpd
      mopidy-soundcloud
      mopidy-spotify
      mopidy-youtube
      mpc_cli
      nyxt
      pulseaudio
      pulsemixer
      scrcpy
      shellcheck
      slack
      sublime3
      sxiv
      synapse-admin
      tagainijisho
      teams
      tenacity
      transcribe
      wireshark
      xcalib
      xclip
      xdotool
      xfce.thunar
      xfce.thunar-archive-plugin
      xfce.thunar-dropbox-plugin
      xfce.thunar-media-tags-plugin
      xfce.thunar-volman
      # xsnow # Wait until christmas
      yuzu-mainline
      zeal
      zoom-us
      zotero
    ] ++ lib.optionals (machineVars.laptop) [
      touchegg
    ] ++ lib.optionals (machineVars.gaming) [
      citra
      desmume
      minecraft
      osu-lazer
      retroarchFull
      steam
      steam-tui
      stepmania
      taisei
    ]
  );
}

