{ pkgs, machineVars, ... }:
{
  home.packages = with pkgs; [
    asciidoctor
    beets
    biber
    python39Packages.bpython
    castnow
    czkawka
    diskonaut
    diskus
    docker
    du-dust
    fd
    ffmpeg
    # gpgtui
    graphviz
    hck
    hexyl
    imagemagick
    jq
    kepubify
    lastpass-cli
    lazydocker
    lolcat
    manix
    mdcat
    mdp
    mediainfo
    megacmd
    megasync
    micro
    mkvtoolnix
    mmv
    mps-youtube
    neofetch
    nmap
    ouch
    pandoc
    python3
    ripgrep
    rsync
    rust-motd
    sc-im
    slack-term
    tealdeer
    # tv-renamer
    toilet
    tokei
    w3m
    waifu2x-converter-cpp
    wavemon
    youtube-dl

    # Needed for VSCode liveshare
    desktop-file-utils
    krb5
    zlib
    icu
    openssl
    xorg.xprop
  ] ++ (
    lib.optionals (!machineVars.headless) [
      ahoviewer
      anki
      audacity
      calibre
      cool-retro-term
      copyq
      darktable
      discord
      fcitx
      geogebra
      gnome.gnome-font-viewer
      google-chrome
      inkscape
      insomnia
      kid3
      koreader
      krita
      ktouch
      libreoffice-fresh
      light
      maim
      mopidy
      mopidy-mpd
      mopidy-soundcloud
      mopidy-spotify
      mopidy-youtube
      mpc_cli
      nyxt
      pulseaudio
      pulsemixer
      scrcpy
      slack
      sxiv
      tagainijisho
      teams
      tenacity
      xcalib
      xclip
      xdotool
      xfce.thunar
      xfce.thunar-archive-plugin
      xfce.thunar-dropbox-plugin
      xfce.thunar-media-tags-plugin
      xfce.thunar-volman
      yuzu-mainline
      zeal
      zoom-us
      zotero
    ] ++ lib.optionals (machineVars.laptop) [
      touchegg
    ] ++ lib.optionals (machineVars.gaming) [
      citra
      desmume
      minecraft
      osu-lazer
      steam-tui
      taisei
    ]
  );
}

