# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "megaraid_sas" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "momiji/root";
      fsType = "zfs";
    };

  fileSystems."/data" =
    { device = "momiji/data";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "momiji/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "momiji/home";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "momiji/var";
      fsType = "zfs";
    };

  fileSystems."/var/lib/postgresql" =
    { device = "momiji/data/postgres";
      fsType = "zfs";
    };

  fileSystems."/var/lib/minecraft" =
    { device = "momiji/data/minecraft";
      fsType = "zfs";
    };

  fileSystems."/data/media" =
    { device = "momiji/data/media";
      fsType = "zfs";
    };

  fileSystems."/data/backup" =
    { device = "momiji/data/backup";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/66C8-A92E";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno3.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
