github:
    tokens:
        prometheus_exporter: ENC[AES256_GCM,data:Uybn/X2kgRKrtoLfgOYU/vR9PS/9JTX4MVuXJBCq2ZH5O2O1W5wfUg==,iv:8Q/kKd3r6G70wU4eLtqpf1obWeErNv5mNrpOQxB6tl8=,tag:PrCMzieirVaCbUT94iVKbg==,type:str]
gitea:
    runners:
        ping: ENC[AES256_GCM,data:DRyw59+KE0n/qEr+Az7r8ulZr3dk1u6hVT1SVqKywW4DgtUr1eLj7DGOXvHxug==,iv:W49dNY/V+6KPuQeN5rdWw6Ed+w/oOy9ey+hRRz7Oxdc=,tag:ILzIKgvLs+8RVpHsSuMHrA==,type:str]
        pong: ENC[AES256_GCM,data:VwpNj/FRSkc5/s6aZPaiBwIaj9VBfp6wcnDFkWmTWC6xRWevMUYKv3jHPhD/ZA==,iv:0uVgjmrF4jIa+Eg3Gofb+2eFa1MdZHb9eR4BcWBpkeQ=,tag:YsXjKqeksU9JcXl+5REXFQ==,type:str]
grafana:
    oauth2_secret: ENC[AES256_GCM,data:zxfPtiB/o5cC27O9uQzPvQV1qWcp3xxnIi7/P84I2lJ/X4ovAwXuiEqnc7BDAE4E,iv:ZY8BDTMEvR2JiFHKM8iM90UQbmTqH/DoVklWno6Xa4U=,tag:E8GTGk9IJauCgjaoToShBg==,type:str]
    secretkey: ENC[AES256_GCM,data:aVzqZqwFfm3FcYJE8USxsDbZVwtnF5NJXTAqshv9av4ZeR5YrDfDzLYHHztXMZt2Q7p/6A==,iv:A7x7oRUVvfxqSXRfi9+15z9pE6xX+GZrGU7gXrSKyXE=,tag:2uatRT0XePk2dqZj2ZlM3A==,type:str]
headscale:
    oauth2_secret: ENC[AES256_GCM,data:Ois+s0O9wgL3zWpgk6E35o5HczIW/4wnSq2KU+F59u4FBFPAtbl/WD0N4AKgWMrm,iv:UX8vhNvHvA5BmNmx5eW8ugce+yZCE1lt2ux8sJajZ8Q=,tag:xOpdLLryt8MptiVsKibNew==,type:str]
hedgedoc:
    env: ENC[AES256_GCM,data:4i2I7S5hKp3mjROMwa3WQinbgmxXhKzSaWspzF12TIDm9g3Bgie0jfSxbDuPjJYq1mZ8oQ2Jzdi2N+Q4blOk9fZO3VREoU0qFrfqm8RqBw3a7hpisXzu9okYnzrW2JiVxNGWwZbuiCG1SzdMOMHq/ZqLEJdu7Pxm9cY9xBSZthap1DCFyr7dmjHt3AnEQemsDpxSaWKD2Dfs1gyA23rLAFBd,iv:lfB6uaXULUNme7cGyN+bKuXPsbgpjMrxrRy2L96HltY=,tag:uu37bZ4g/PA2mgzs3ioLCQ==,type:str]
cloudflare:
    api-key: ENC[AES256_GCM,data:dqKGLnIlPAgBNTxcRo6Q55hKoe8Qg9UCmDvJioJdhBxmjTXQrf0LFL/iMC73K+Kj0ejuzBRJaqfN6548aZZTSDb8hPTygh7PEILqdxNrap9uDm229eJM/zrShOIRaNLH,iv:pUkuU3Es20ujDtOYfGZodxEUZSlfAe/45ewEkPG1GP4=,tag:sA7nMLldPRRo0jwcdF34ng==,type:str]
drives:
    cirno:
        credentials: ENC[AES256_GCM,data:ypMZhs7dQw/IlcLwHwFcIZw0N+kCzvFGLe3gEqZVe1hj0lzK8MCfxAR8GpA=,iv:by5ljMzOuuY4b6BDUQNLhp8/gcXDNe+rHkqhFzjNA6c=,tag:3C5iYsxEWwAKs9Blgr5o6g==,type:str]
nextcloud:
    initialPassword: ENC[AES256_GCM,data:ROG+4u6C9zBu8Ez3Jprw8cgwVd2gFErUIOBmrWL9o7/qSGPT8jnwd0T5W8E=,iv:uRdL/3Xslu/J/aPI44WxlNw3RLAvjDRPt5VttuQL/P0=,tag:IDmGXNF9PsHPaMqK5YUKIg==,type:str]
postgres:
    gitea: ENC[AES256_GCM,data:HyYgEgOzeOnaEvPDEXoL+fRhrnqCeGbb/wOYf2kHulxrU9PKIAcRzmNljsc=,iv:1N/N2RUQ++rAWw4VNQzhee2aV9LzOJym6cyM6CAnZUU=,tag:o7dblJrIAPd4/S8X2LKdcQ==,type:str]
    invidious: ENC[AES256_GCM,data:r/Jzs7U1fkCi2j5L/tOcBfakR3virj8HGrDrVZdP7VwubG4BJLvoeb14eJo=,iv:3plNFOds+HeF0HAliedczpNgPL4ZgqhCOwqbnb2e8Ag=,tag:DHm/KM9UuPiqaRxqNDb7QA==,type:str]
    nextcloud: ENC[AES256_GCM,data:E1tD6Z2SDbi5TUDAACjXSJJIn+/ySu0+8xhvRVFxumxjex4ZsEw+mofKIxM=,iv:E4iPVF3M8GOoQghVQtn/kCEpXl0b8MueCbtyvzFM8AA=,tag:IF4kWOuTsylqrXMoXzQaVQ==,type:str]
    headscale: ENC[AES256_GCM,data:UVPCZjcpm9j2dMwyAvrPfwOj84JJHrwoU5rs672FEeA=,iv:zq3J4mL/PB3EAl8LHxxC77Y4FMrZWT4QF+DOih+FIGk=,tag:UwfjKnjfJ3a6RwAWg/8BzQ==,type:str]
    grafana: ENC[AES256_GCM,data:bsxzS/xkNdSJvOSQfZY8RRK03ckfKAoYeiZlgrSxXVqTEQ==,iv:wb8bFITgGLToagEczdm7MwUmXl3tyYmrYqSZOblEz0I=,tag:ZboMGI4QdmOK+LVBDCl2Pg==,type:str]
    matrix_synapse: ENC[AES256_GCM,data:hLlUeo6glgw1PIo4N9aE7KLg7JV88EcG4IYZwVhs97Y=,iv:c4g33QQ/r54KrBM/zUG/gS9rNQy1OUB4KPSAggkgNvo=,tag:WOezFIPE89+oHKGMrsMSgA==,type:str]
paperless:
    password: ENC[AES256_GCM,data:8ut0DX8NajIy/WUwd3eBrFiGwsTMTYKWaPDy7kGytt8=,iv:q2hTmQsS4kBLZ4I7nRljstHlqELsGBYqf5yifFh3vNY=,tag:eJj+DXU898frl6+IoBsSPQ==,type:str]
matrix_synapse:
    oauth2_secret: ENC[AES256_GCM,data:w5Jn/YwQ0zH0FUtt2s3mt1+bvo4Ka7l3rnV6F7QfqQdoIq+6N47poEY4OYkAGReW,iv:GZOAHhwt5mjkScdpU+EY9bWUnyouJrc9LhjxvxuCSQ8=,tag:o6It7qTehwErXTBakYX5tg==,type:str]
    registration_secret: ENC[AES256_GCM,data:TLeuMKVkiMyz/vs/ksUj688qtlAS5t87qw7HCUP4rtTlXfG7Hu0zrgiDVU1BAiLzwEFxgLEaEl1CHdtCVSFUD26Uz7YZzWxD5EAfOkn3MZLQVK8bopeqAJFjnq3D/Z0kV9vl+t1iRtKbxcrgXwYZkEMct71SnNVZWYTOSnkTcGgyEwcy/m7wDtcy0L6GL7XU/4LP+qZtZjb4sygFMCIOKAuF7RWaBzPPee/66mLyPuiDxGm8vGycEnmeQ2GtdtDuxtr9IQ0jqB5AlkHtVLFrpJXesupzMGoKaXJiQKMgTgm4O6ygbliHZbhZ0NOOrVoh7zxa7BTYhpxeM6/g+tSTqw==,iv:ZNyjBRjxDorc1kC8LR+O7JilpZuf9tu6baS187VnHA0=,tag:kL4xf8Xl4U9cPktkcx+bZw==,type:str]
    turn_shared_secret: ENC[AES256_GCM,data:0XHTDom8ZurRz+CbFmjjLpm97w4njoVGSHivuN9uve0=,iv:O8qcmrFLjHLgqhSzb2RavQl+RBUnK+Wid5KvfFaB08E=,tag:oajdWa5O/Gqu4OiSGbzNqQ==,type:str]
osuchan:
    envfile: ENC[AES256_GCM,data:gaO+3haU1jMkqRm1PiSSd4oTcoPvgbsRHWfhPnXJbFSv4cXsqeS1xRrbZZftu5g2nfr+vb8ljtmGyk3dVLOHo5SzVQlJzcJNKoVp9XTLlmbC1AuKjxv3p7dWyD71n5reO52uDlbNJQPMzgOw70DM7wTffCaLbDUIyB+bPcESxiYHC2S3kITZErCdJczEKpRPjS0wM9kjENN9HN1WobhquZ1w7gXfXIx174QUV3LdJMrhaibzDZEu4dBaxVkxbKRa78bPNCN6LVD4U1woG0IeIh6CGCGtGghIkhcUIZsUauXPw7g/uQHPcJF3/h64I7477j9D1Qrrz0bN3kU9jyAro5jv1hcRUS6b,iv:zbJol31niHWz+0DXGE4vm2T7aXAZfbdj0rN7xlSctGg=,tag:kDCQUPjeHWMWQ22tE8ar4A==,type:str]
ssh:
    nix-builders:
        bob:
            key: ENC[AES256_GCM,data:CfzF32ELxePyls+JgxLRN3HeIyRGnH5G5MRuL23YGZ5DqBqjIjgoL64zzHB2tIn9D8RjUzmYxU7y70mwoej0V/Vr3qHtUkv2tC+XXw0uN4Be9n5iMo52Ovi+ZE4BVkKE94Y98YZtr0IbbjmgYAj+FS30lfld1KydKfmQUhzijIX8zUchL3spFwdxZSFQv2skXetEu9eIGMYeSTd7CSNk72zVONaW5s0cdKH0iLcO27CyzB3qArdn27gBbgn0rHvoaEvEMJGz4h4RHjk+JIU9+PKEqU8LMZOSYmD2wumX9W4s2L+YC5b5CDUvHaP0+n2bilpYCRuBlWMIzrNgkKyszVeNL+UnDM2nl1pF+ymapyrfyOGALuBoFd61uqE94/cCX21DAEB6E7SZtkQI/inKk1Wm7rvKEmTCjpHRNLf2J5i1IeePeHp1/ODHTfWZogtxh/SjpsR/ioGbt2X5yUvX+Xb6Ks35YwNyxVyXYV5azD60oQF/FSFwqNqRiNX/UE7a+FDwFgDoPleDOvJcv/35QZM6c9xYfWtUioKc,iv:LPQ+eJNeuL0SQRr1crRR2t4nZSanOihNrUK0mtdI3so=,tag:GjTZ+VbxYAqNDVg9m3IDVw==,type:str]
            pub: ENC[AES256_GCM,data:6MbJXoYF6cV7EOMXOiaELf0TOSnTT2uO57U+05iqZ4wkIuCS+VQfsoxO7KqbGDKdBJUKC6ec2dcoKgKO8f7sPdCiZRpg4oa3y7NtjHAI+Y+ST9KqtuNBYkuR4MqAPdFw,iv:8opIUO5rx50sRTTYHMvUXWifYMsx4lBrSRe9cZauB0g=,tag:KL+hS1gLeNXPi7Xm/j1iYA==,type:str]
        tsuki:
            key: ENC[AES256_GCM,data:Egj12NoJk30pZ/jmsXjCalT3iGyhCE9x65SeIIGS+oJfcHSaIMEc6oihw4W6TQ3/0+arwBp1x1jlVTZZH0qMKBkFqZsRGdDboY/0BGulqUpn93GknTtqc0kMXIWhdG7luHhqxTN8fjAdUsAvMCWiarkfqrKCodxDdnIUJDcOap2HGS3BzTHaY01BqoDNAtAJlv10DiQNejpP0q9i9RvTKeDjcQQWUvlWDb8TlHw4iLxJcbtw41sHXbvZzGpn6S6AilsVGZ697u6whf0ybow+vXOVPuC03KSns61g8yPFN10dn+9deZz6xN/PhUHwdAuaMjnFaMy7VDkkb2kbgtfOjCPRW5CWIaMm5eYx6HYcxqWSZkrYVyqrgFrwSi72P8MX7lRuWq5QrJdpdo/Wm8dw1tgK5uIope/Uy89UgRYQodwGu7P3aSH/01q+tTj3z6AxNUEAKPOfTwu7n8Vyjjv26jlpIfiOlMys41R3qWeUztihWNc1XoAuqIdIjbyK0AIafFAcOW1izbK+uO1y63u3,iv:LQu0rgYj9jxDXm0LlIxoedYNqZNVHz2zG1KXypcjQhY=,tag:TwRlvhrSxqW/vipVPzEdKA==,type:str]
            pub: ENC[AES256_GCM,data:nuXr2swvEV7sk6s8wU3xTOzpo1Ld/4K+K9EyVCOOXT5h+wvH/ToXItcs6boeOKVccZLJoleaCLfJ2r5xK4XGgLjZI+ycoEEikpJz09qLkHxpqwE5a2kFVFCPoQ==,iv:EaYqyqmzCKg9nEdU67l7WjzpZrXGXej9LxjgS2kSxAQ=,tag:tgqTp62P6BYVFyQp1LO8tg==,type:str]
        isvegg:
            key: ENC[AES256_GCM,data:RD+QCA6hzSihe9ASaug4S1U6vrIA34UIH7WXlEPQ/nLkAd05uYKQanYvyQzx1xbZha0m3rqoiR/SN9FynSFUZOxrRZM52pq4VoZQkyijfSp9QQwz1HKnhzZlwlLtvp/meAhnbLEacQjgg30uw1tvQJR81RsCnNInGlPXSaZzPUx34/zqCtt55zj9t5oYThPPsJV23sgnc2sMIe8o+IaNtGdnrJMaW141jeC7OkDZLBSOXkeUYbjED8tovmhVvhzm3CLUkXikSAL89CzyuHg6a2R6cmaOa3P4DUkRjwVW2Wznc5GlcoAhxL/+bRcGCK3orEtD0O/YLgHWrKLW8cmTVAan4EbjWY4Dgo5SXYCNUdP3YuJwTQXqcMsuX7uINcVeQ+K1EYXjf/c8TtLwwI0Vw0bYir+qkp4My0nJzVSmKxLyyi8KzBPjXQxgkEOES5VZM1R/FnrpPjrTZ2Kyx8vZ49rPkc6ClE8zZ2Ac4zKCgzkMtbTEVRIgj/bZmF3MtBgBVepukFGGEaCrpV2Yj0O3,iv:/nSDu/J9FHGfFTyLrIClwhcaXLNH38ubXW0ix+G75dE=,tag:1ifm89yxDrsnViPU9fq20A==,type:str]
            pub: ENC[AES256_GCM,data:TaB+UN5w2nAnJaWAa5DZ7P/0hs5212YbJUmLLhqrbgl2zn4O1qQET4gY1HNKYaf+4HqJujhBEcxFp/XJaQ9/q/YSX3JMnE0IIBeNMqC/o/yPaGgj/dawvBa3bQ==,iv:pTIdUkIeRTUsaj0fydkVB9PGaZy2WcSsGa42th4rDGY=,tag:D+kSKmCHO/brBP6SRMo4Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c92j4w0gqh32hwssl5m2mfrggssxax9pge8qxwytv9lmrnfttcvqdrgsst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cmVUbVJLNTcrWElnRFV5
            djNBRlg1SUE1UDJHaXRXSkxoZXpZbGpySVhzCnNDVG5iM0VmMmF6NFArNDUweXBq
            dFZ1L0RRSVlSa1hlMGNMaXpzdFNTVWsKLS0tIHpFR2dmaTFIaVNaOFZMeVRUejVs
            bHJvenMwME1Gd1Z1Qm9kYVNkYkVsVVkKPCph78R5qMrKaofPpW6O5mjEcIPVvlwG
            nIv679EhVUgUR3Zln/egICOj20SzzZzmDdBc7VbaZDiz3dyRbe5D8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eu2a6m3adakfzelfa9pqpl74a5dz0wkyr0v7gegm5ajnx7aqmqcqsp2ftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL0tDUDhibEplaERzQThG
            ZElwM0V2MTJROEtucWdFdTR5bHE1cktGYkZzCnVDd0lZdmZNWUtYeHV4dG9GVEsy
            dzBnd0szakNjZWpSVWtQY0tZTWZncEEKLS0tIE1aWkE4S3VBblFSVjMranNSYWoz
            cElPYm5qK2lkTWZ1UGd6TU1NV2h4OTgK8Ecv58Ybnc6iYMjtSKTT1fYbNf4yyFgX
            rjQ2sU8Rqc04MqixnAkF2zSDaaJ0vqwf22MvbO3bYhpqOHwiTMbRLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T13:40:50Z"
    mac: ENC[AES256_GCM,data:dMMYtUSNPB8wq/HnFYctRhpU4uHbQfA7k/EkP4pGU0RJUfvcnAtU5KCN+WpcWPNN3xBESJ3mjDGlYp2GrdoGPfj/f/+sJd2OdgPDAagb8yRCTBmQyvnv72WCxZTcV4BkBAJJQKSiTIxZ5q/t83LxzgXJ0mQnpDXFEBNf7sLJr84=,iv:Ga9URI5SbT456/LfFAlYlRu+/TAYTC+k/AKKCL2bHMM=,tag:2lqME8FFL5/BK/vN5FA1GA==,type:str]
    pgp:
        - created_at: "2023-05-08T00:49:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0av/duuklWYAQ/+Oh1FcH1sA8Rf0R/38u5mFgAW2uRdC2KeUNh2qtBtwmTf
            W3r9vmD+9UUlppxk2/o82yIecXsv8Bz4/e/04Xo8b0sfBB+l+odVY72mTBUGYQjQ
            +7B9PT5ZGBuWXOTTWmaYX11CFPw7KaPjS7k2Z3VoZXaOMa5vQUUzjCdw9N/y8nnV
            Gl3ThHd0CEJ95iemV/CPS72h2Yf4jbk4WVdqDBtYxkv0VWMMOfjeaOPqQJKVDWDv
            Bg9TQEoucfi4kYG5pR1NY5S0W73XU4ND+V9laeKdW47TUAtw56ajWAglTUZZ6+I8
            xtm25neL90VIKQrKJTzp9IynjdDpuD9ZVNCQLg4UqbxTAcvLNgXGG5iDpr72asUO
            kOg1dCT00o++7SsGp9cA3+0Z1H5QKnJ3ekt2XyyD5pEDCdLwbotaDZEdST3usWR7
            k80Q5GfkBdE5RwvqfPEIDhwwtLnvI/lgyq1l4S/g3dNzV8vQauBQKcDWy+ZT8Kdk
            u5DdfL4hxA04/a7VORFzwQMdm97VRIfOXA2pscDX+83drwtvdmTbvReigLHkS2pz
            Xq1IDJSlJjJX0Yb2vbIXwLrfXrIbarnft0tb3TTZAK0B7yvLKbvLT0EZWAndssUw
            Utymmi2S6NvomebjAanqlWOTvgFaSBiG/tlILFPSBeAl1/mD9ijVgMq+QfdtoyHS
            XAHkesaQ2U2HmuObPQioIYYvfMCSuFEClqgumWSSa4nLNmSulW3DYlvnKZJ17iAI
            1p9X1xYS00t3dmbne7Q2DAkPBqB0JbgMBpJ9RNfyJdBAdNrRh3+x1k2mTA0I
            =wF/N
            -----END PGP MESSAGE-----
          fp: F7D37890228A907440E1FD4846B9228E814A2AAC
    unencrypted_suffix: _unencrypted
    version: 3.8.1
